[package]
name = "render_engine"
version = "0.1.0"
authors = ["Iamthetoaster"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.25.1"
glutin = "0.22.0"
image = "0.22.3"